language: python
python:
  - "3.6"
install:
  - pip install PrettyTable
  - pip install python-dateutil
  - sudo apt-get install -y r-base
script:
  - python -m unittest sprint1_alltests.py
  - python -m unittest sprint2_alltests.py
