- os: windows
  language: sh
  python: "3.7"
  before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
  script:
   - python -m unittest sprint1_alltests.py
   - python -m unittest sprint2_alltests.py
   - python -m unittest sprint1_alltests.py
